### ISSUE TITLE
very verbose logging for missing property

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#1111]
An optional property in #765 is leading to lots of logging like this

```
12-489: No configuration setting found for key 'pekko.cluster.akka'
com.typesafe.config.ConfigException$Missing: merge of String: 2-7,system properties,reference.conf @ file:/home/runner/work/incubator-pekko/incubator-pekko/cluster/target/scala-2.13/classes/reference.conf: 12-489: No configuration setting found for key 'pekko.cluster.akka'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:157)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:150)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:177)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:181)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:181)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:194)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:251)
	at org.apache.pekko.cluster.SeedNodeProcess.akkaVersion$lzycompute(SeedNodeProcess.scala:61)
	at org.apache.pekko.cluster.SeedNodeProcess.akkaVersion(SeedNodeProcess.scala:56)
	at org.apache.pekko.cluster.SeedNodeProcess.receiveJoinSeedNode(SeedNodeProcess.scala:84)
	at org.apache.pekko.cluster.JoinSeedNodeProcess$$anonfun$receive$2.applyOrElse(SeedNodeProcess.sc
```

**Comment by pjfanning** [comment]
fixed in https://github.com/apache/incubator-pekko/pull/1112
