### ISSUE TITLE
Build fails on windows

### ISSUE THREAD

**Issue by sdeigm** [apache/incubator-pekko#73]
Building the project on windows using sbt compile fails with the following exception:

`[info] welcome to sbt 1.7.1 (Temurin Java 1.8.0_332)
[info] loading settings for project incubator-pekko-build from plugins.sbt ...
[info] loading project definition from C:\Entwicklung\incubator-pekko\project
[info] loading settings for project pekko from build.sbt ...
[info] resolving key references (62652 settings) ...
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
        at java.util.regex.Pattern.error(Pattern.java:1969)
        at java.util.regex.Pattern.compile(Pattern.java:1708)
        at java.util.regex.Pattern.<init>(Pattern.java:1352)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at java.lang.String.split(String.java:2380)
        at java.lang.String.split(String.java:2422)
        at org.apache.pekko.PekkoValidatePullRequest$$anonfun$$nestedInanonfun$buildSettings$1$1.applyOrElse(ValidatePullRequest.scala:49)
        at org.apache.pekko.PekkoValidatePullRequest$$anonfun$$nestedInanonfun$buildSettings$1$1.applyOrElse(ValidatePullRequest.scala:47)
        at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:145)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.collect(TraversableLike.scala:407)
        at scala.collection.TraversableLike.collect$(TraversableLike.scala:405)
        at scala.collection.AbstractTraversable.collect(Traversable.scala:108)
        at org.apache.pekko.PekkoValidatePullRequest$.$anonfun$buildSettings$1(ValidatePullRequest.scala:47)`

The problem is caused by using the file.separator system property as regular expression in ValidatePullRequest.scala:49. On Windows this is the backslash which is not a valid regular expression.

The problem can be fixed by using a hardcoded slash as splitting regular expression. This also works on windows.

**Comment by pjfanning** [comment]
@sdeigm any interest in submitting a PR yourself? A lot of us don't have Windows machines to try out build changes like this. The CI build will find out if you break the Linux build.

**Comment by sdeigm** [comment]
Ok, I will give it a try.
