### ISSUE TITLE
ByteStringBuilder can stackoverflow when call addAll with LinearSeq

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko#900]
```scala
      ByteString.newBuilder.addAll(List[Byte]('a'))
```

results:
```scala
java.lang.StackOverflowError
	at org.apache.pekko.util.ByteStringBuilder.addAll(ByteString.scala:1082)
	at scala.collection.mutable.Growable.$plus$plus$eq(Growable.scala:69)
	at scala.collection.mutable.Growable.$plus$plus$eq$(Growable.scala:69)
	at org.apache.pekko.util.ByteStringBuilder.addAll(ByteString.scala:1193)
	at org.apache.pekko.util.ByteStringBuilder.addAll(ByteString.scala:1082)
	at scala.collection.mutable.Growable.$plus$plus$eq(Growable.scala:69)
	at scala.collection.mutable.Growable.$plus$plus$eq$(Growable.scala:69)
	at org.apache.pekko.util.ByteStringBuilder.addAll(ByteString.scala:1193)
```

seems like some overloading issue.

**Comment by pjfanning** [comment]
@He-Pin @mdedetrich I have a possible fix in https://github.com/apache/incubator-pekko/pull/903

**Comment by pjfanning** [comment]
Until we get a new Pekko 1.0.3 release out, the workaround is to use `++=` instead of `addAll`.
