### ISSUE TITLE
failed: ClusterActorLoggingSpec

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko#929]
https://github.com/apache/incubator-pekko/actions/runs/7482391595/job/20365886171#step:6:859
```scala
<-- [org.apache.pekko.cluster.typed.ClusterActorLoggingSpec: Logging from an actor in a cluster must include host and port in sourceActorSystem mdc entry] End of log messages of test that [Failed(java.lang.AssertionError: Timeout (20 seconds) waiting for 1 messages on LoggingTestKitImpl(1,Some(INFO),None,None,Some(Starting),None,None,Map(),true,Some(org.apache.pekko.cluster.typed.ClusterActorLoggingSpec$$Lambda$1694/0x0000000800ad6040@4ccd169d)).)]
[info] - must include host and port in sourceActorSystem mdc entry *** FAILED *** (20 seconds, 10 milliseconds)
[info]   java.lang.AssertionError: Timeout (20 seconds) waiting for 1 messages on LoggingTestKitImpl(1,Some(INFO),None,None,Some(Starting),None,None,Map(),true,Some(org.apache.pekko.cluster.typed.ClusterActorLoggingSpec$$Lambda$1694/0x0000000800ad6040@4ccd169d)).
[info]   at org.apache.pekko.actor.testkit.typed.internal.LoggingTestKitImpl.expect(LoggingTestKitImpl.scala:113)
[info]   at org.apache.pekko.cluster.typed.ClusterActorLoggingSpec.$anonfun$new$2(ClusterActorLoggingSpec.scala:63)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1240)
[info]   at org.apache.pekko.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:79)
[info]   at org.apache.pekko.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:77)
[info]   at org.apache.pekko.cluster.typed.ClusterActorLoggingSpec.withFixture(ClusterActorLoggingSpec.scala:40)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1238)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1250)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1250)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1232)
[info]   at org.apache.pekko.cluster.typed.ClusterActorLoggingSpec.runTest(ClusterActorLoggingSpec.scala:40)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1309)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1309)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1308)
[info]   at org.apache.pekko.cluster.typed.ClusterActorLoggingSpec.runTests(ClusterActorLoggingSpec.scala:40)
[info]   at org.scalatest.Suite.run(Suite.scala:1114)
[info]   at org.scalatest.Suite.run$(Suite.scala:1096)
[info]   at org.apache.pekko.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.org$scalatest$BeforeAndAfterAll$$super$run(ScalaTestWithActorTestKit.scala:41)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at org.apache.pekko.cluster.typed.ClusterActorLoggingSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(ClusterActorLoggingSpec.scala:40)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1354)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1354)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1352)
[info]   at org.apache.pekko.cluster.typed.ClusterActorLoggingSpec.run(ClusterActorLoggingSpec.scala:40)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:414)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by He-Pin** [comment]
https://github.com/apache/incubator-pekko/actions/runs/7695679477/job/20969089026#step:6:875
